root = "."
tmp_dir = "tmp"

[build]
bin = "./tmp/server"
cmd = "go build -buildvcs=false -o ./tmp/server ./cmd/server"
delay = 1000
exclude_dir = ["tmp", "vendor", "docs"]
include_ext = ["go", "env"]
kill_delay = "0s"
log = "build-errors.log"

[color]
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = true

[misc]
clean_on_exit = true
